# regular NLL, only do concept forcing for RL
python bin/train.py config/RRG/baseline-mimic.yml \
    dataset.seq.processing=ifcc_clean_report \
    dataset.image.root=data/RRG/mimic-cxr/findings/ \
    dataset.seq.root=data/RRG/mimic-cxr/findings/ \
    dataset.seq.file=findings.tok \
    dataset.seq.tokenizer_max_len=128 \
    dataset.image.file=image.tok \
    dataset.image.image_path=data/images/ \
    dataset.image.multi_image=3 \
    model.cnn.backbone=densenet121 \
    model.cnn.visual_embedding_dim=1024 \
    trainor.batch_size=16 \
    trainor.grad_accu=8 \
    trainor.optim_params.lr=0.0003 \
    trainor.optimizer=Adam \
    trainor.early_stop_metric=bertscore \
    trainor.early_stop=10 \
    validator.batch_size=8 \
    validator.beam_width=2 \
    validator.metrics='[bertscore]' \
    validator.splits='[validate]' \
    ckpt_dir=ckpt \
    name=nll_findings_bioclinical_bertscore_128

# nll_checkpoint=ckpt/nll_findings_bertscore_128/0.554715_6_736581.pth
# python bin/train.py config/RRG/baseline-mimic.yml \
#     dataset.seq.processing=ifcc_clean_report \
#     dataset.seq.root=data/RRG/mimic-cxr/findings/ \
#     dataset.seq.file=findings.tok \
#     dataset.seq.tokenizer_max_len=128 \
#     dataset.force_seq.processing=ifcc_clean_report \
#     dataset.force_seq.root=data/RRG/mimic-cxr/concepts/ \
#     dataset.force_seq.file=all_concepts.tok \
#     dataset.force_seq.tokenizer_max_len=128 \
#     dataset.image.root=data/RRG/mimic-cxr/findings/ \
#     dataset.image.file=image.tok \
#     dataset.image.image_path=data/images/ \
#     dataset.image.multi_image=3 \
#     model.proto=RRG_SCST \
#     model.top_k=0 \
#     model.ckpt=${nll_checkpoint} \
#     model.scores_weights='[0.01,0.495,0.495]' \
#     model.scores_args='[{},{reward_level: partial}]' \
#     model.scores=[bertscore,radgraph] \
#     model.use_nll=true \
#     model.cnn.backbone=densenet121 \
#     model.cnn.visual_embedding_dim=1024 \
#     trainor.batch_size=12 \
#     trainor.optim_params.lr=5e-5 \
#     trainor.optimizer=Adam \
#     trainor.grad_accu=2 \
#     trainor.early_stop_metric=bertscore \
#     trainor.early_stop=3 \
#     trainor.lr_decay_params.patience=0 \
#     trainor.lr_decay_params.factor=0.8 \
#     validator.batch_size=16 \
#     validator.beam_width=2 \
#     validator.metrics='[bertscore,radgraph]' \
#     ckpt_dir=ckpt \
#     name=rl_findings_constrain_concepts_bertscore_128

# python bin/ensemble.py config/RRG/baseline-mimic.yml \
#     dataset.seq.processing=ifcc_clean_report \
#     dataset.seq.root=data/RRG/mimic-cxr/findings/ \
#     dataset.seq.file=findings.tok \
#     dataset.seq.tokenizer_max_len=128 \
#     dataset.force_seq.processing=ifcc_clean_report \
#     dataset.force_seq.root=data/RRG/mimic-cxr/concepts/ \
#     dataset.force_seq.file=all_concepts.tok \
#     dataset.force_seq.tokenizer_max_len=128 \
#     dataset.image.root=data/RRG/mimic-cxr/findings/ \
#     dataset.image.file=image.tok \
#     dataset.image.image_path=data/images/ \
#     dataset.image.multi_image=3 \
#     model.proto=RRG_SCST \
#     model.top_k=0 \
#     model.scores_weights='[0.01,0.495,0.495]' \
#     model.scores_args='[{},{reward_level: partial}]' \
#     model.scores=[bertscore,radgraph] \
#     model.use_nll=true \
#     model.cnn.backbone=densenet121 \
#     model.cnn.visual_embedding_dim=1024 \
#     ensemblor.batch_size=16 \
#     ensemblor.beam_width=2 \
#     ensemblor.metrics='[bertscore,radgraph]' \
#     ckpt_dir=ckpt \
#     name=rl_findings_constrain_concepts_bertscore_128