nll_checkpoint=0.554715_6_736581.pth
concept_type=all_concepts
python bin/ensemble.py config/RRG/baseline-mimic-force.yml \
    dataset.seq.processing=ifcc_clean_report \
    dataset.image.root=data/RRG/mimic-cxr/findings/ \
    dataset.image.file=subset.image.tok \
    dataset.seq.root=data/RRG/mimic-cxr/findings/ \
    dataset.seq.file=subset.findings.tok \
    dataset.seq.tokenizer_max_len=128 \
    dataset.force_seq.processing=ifcc_clean_report \
    dataset.force_seq.root=data/RRG/mimic-cxr/concepts/ \
    dataset.force_seq.file=subset.${concept_type}.tok \
    dataset.force_seq.tokenizer_max_len=128 \
    dataset.image.multi_image=3 \
    model.cnn.backbone=densenet121 \
    model.cnn.visual_embedding_dim=1024 \
    ensemblor.batch_size=1 \
    ensemblor.beam_width=2 \
    ensemblor.metrics='[BLEU,ROUGEL,CIDERD,bertscore,radgraph,chexbert,radentitymatchexact,radentitynli]' \
    ensemblor.splits='[test]' \
    ensemblor.prune_factor=200 \
    ensemblor.sat_tolerance=2 \
    ensemblor.alpha=0.05 \
    ensemblor.beta=0.25 \
    ensemblor.look_ahead_step=4 \
    ensemblor.look_ahead_width=2 \
    ensemblor.fusion_t=1 \
    ensemblor.ckpt=${nll_checkpoint} \
    ckpt_dir=ckpt \
    name=nll_findings_${concept_type}_constraints_gt_4_bertscore_128